elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "8000:9200"
    - "9300:9300"
logstash:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - /home/docker-user/docker-elk/logstash/config:/etc/logstash/conf.d
    - /mnt/logs:/logs
  ports:
    - "5000:5000"
  links:
    - elasticsearch
kibana:
  build: kibana/
  volumes:
    - /home/docker-user/docker-elk/kibana/config/:/opt/kibana/config/
  ports:
    - "80:5601"
  links:
    - elasticsearch
